// Generated by gencpp from file Taskpkg/complex.msg
// DO NOT EDIT!


#ifndef TASKPKG_MESSAGE_COMPLEX_H
#define TASKPKG_MESSAGE_COMPLEX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Taskpkg
{
template <class ContainerAllocator>
struct complex_
{
  typedef complex_<ContainerAllocator> Type;

  complex_()
    {
    }
  complex_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::Taskpkg::complex_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Taskpkg::complex_<ContainerAllocator> const> ConstPtr;

}; // struct complex_

typedef ::Taskpkg::complex_<std::allocator<void> > complex;

typedef boost::shared_ptr< ::Taskpkg::complex > complexPtr;
typedef boost::shared_ptr< ::Taskpkg::complex const> complexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Taskpkg::complex_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Taskpkg::complex_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace Taskpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Taskpkg::complex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Taskpkg::complex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Taskpkg::complex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Taskpkg::complex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Taskpkg::complex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Taskpkg::complex_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Taskpkg::complex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::Taskpkg::complex_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::Taskpkg::complex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Taskpkg/complex";
  }

  static const char* value(const ::Taskpkg::complex_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Taskpkg::complex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::Taskpkg::complex_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Taskpkg::complex_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct complex_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Taskpkg::complex_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::Taskpkg::complex_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TASKPKG_MESSAGE_COMPLEX_H
